### ISSUE TITLE
ImportError: cannot import name 'DistShift2' from 'gym_minigrid.envs'

### ISSUE THREAD

**Issue by furqon3009** [lifelong-learning-systems/tella#307]
I got an error when trying to run the example code for dqn agent using this command: python examples/rl_dqn_agent.py --curriculum SimpleCartPole

Then I got this error:
/home/user/anaconda3/envs/tella3/lib/python3.7/site-packages/gym/envs/registration.py:307: DeprecationWarning: The package name gym_minigrid has been deprecated in favor of minigrid. Please uninstall gym_minigrid and install minigrid with `pip install minigrid`. Future releases will be maintained under the new package name minigrid.
  fn()
Traceback (most recent call last):
  File "examples/rl_dqn_agent.py", line 35, in <module>
    import tella
  File "/home/user/Reinfocement Learning/tella/tella/tella/__init__.py", line 31, in <module>
    from ._curriculums import load_curriculum_registry
  File "/home/user/Reinfocement Learning/tella/tella/tella/_curriculums/__init__.py", line 23, in <module>
    from tella._curriculums.minigrid.simple import SimpleStepMiniGridCurriculum
  File "/home/user/Reinfocement Learning/tella/tella/tella/_curriculums/minigrid/__init__.py", line 22, in <module>
    from .simple import SimpleMiniGridCurriculum, SimpleStepMiniGridCurriculum
  File "/home/user/Reinfocement Learning/tella/tella/tella/_curriculums/minigrid/simple.py", line 22, in <module>
    from .m21 import SimpleCrossingS9N1, DistShiftR2, DynObstaclesS6N1
  File "/home/user/Reinfocement Learning/tella/tella/tella/_curriculums/minigrid/m21.py", line 26, in <module>
    from gym_minigrid.envs import (
ImportError: cannot import name 'DistShift2' from 'gym_minigrid.envs' (/home/user/anaconda3/envs/tella3/lib/python3.7/site-packages/gym_minigrid/envs/__init__.py)

**Comment by cash** [comment]
Thanks for the report @furqon3009. I've fixed the dependency issue and deployed version 2.1.0 to PyPI.
